### ISSUE TITLE
Add twitter pull functions for major PSE twitter accounts

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#1]
Will create functions that pull and listen to specified PSE related account:

Examples are the official PSE and stock brokerage accounts:

https://twitter.com/phstockexchange?lang=en
https://twitter.com/colfinancial?lang=en
https://twitter.com/firstmetrosec?lang=en
https://twitter.com/BPItrade
https://twitter.com/Philstocks_
https://twitter.com/itradeph
https://twitter.com/UTradePH
https://twitter.com/wealthsec

For COL, listening to  #COLResearch specifically will filter to the analyst reports.

Note that acronyms preceded by a "$" are stock tickers, so we can use this to identify the company that a tweet is about (e.g. $MWC).

**Comment by enzoampil** [comment]
Can use this scraper [link](https://gist.github.com/onmyeoin/62c72a7d61fc840b2689b2cf106f583c)

**Comment by rafmacalaba** [comment]
@vincevertulfo the `SentimentStrategy` is ready to accommodate this one. Please ping me if you want to integrate it na to fastquant.

**Comment by jpdeleon** [comment]
Related #187

**Comment by enzoampil** [comment]
Since above functionality is already available with the latest PR, I'm okay closing this :smile:
