### ISSUE TITLE
[R FEATURE] Mirror get_stock_data with yahoo finance integration for R

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#109]
Currently, we can only to `get_pse_data` with `R`. To make it consistent with the python package, it's best to have a version that includes global stock data with the same yahoo finance API.

**Comment by jgendrinal** [comment]
The following issues have this issue as a dependency: https://github.com/enzoampil/fastquant/issues/106 https://github.com/enzoampil/fastquant/issues/102

**Comment by enzoampil** [comment]
Using quantmod

https://cran.r-project.org/web/packages/quantmod/quantmod.pdf

**Comment by jgendrinal** [comment]
quantmod implementation included in CRAN submission. Will revise locally given any CRAN feedback, then will make the pull request that will close this issue.

**Comment by enzoampil** [comment]
Already done, just waiting for CRAN release :)
