### ISSUE TITLE
[BUG] pip install from master does not work

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#110]
Ever since the new R file system got implemented it now doesn't work to pip install straight from master.

Example:

```
!pip install -U git+https://github.com/enzoampil/fastquant.git

Collecting git+https://github.com/enzoampil/fastquant.git
  Cloning https://github.com/enzoampil/fastquant.git to /tmp/pip-req-build-kv47gy11
  Running command git clone -q https://github.com/enzoampil/fastquant.git /tmp/pip-req-build-kv47gy11
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jpdeleon** [comment]
For the meantime, should we revert to previous version and develop R on a separate fork, so at least master works?

**Comment by enzoampil** [comment]
@jpdeleon Apologies, latest PR merged should've fixed this. Please let me know if you still encounter any issues.

**Comment by jpdeleon** [comment]
Yep, now it works.
