### ISSUE TITLE
[FEATURE] add multi-strategy

### ISSUE THREAD

**Issue by ChingSlayer** [enzoampil/fastquant#113]
Feature Suggestion
- A backtest/trade strategy which incorporates multiple indicators 

Example:
- Buy when Price > 20 ema > 50 ema > 100 ema AND StochasticRSI is oversold
- Sell when close is below 20 ema

Position Size/Risk Mgt: 
- Risk 2% of portfolio every trade

**Comment by rafmacalaba** [comment]
@enzoampil this one seems to be customized as per user, how do you want to call this? @ChingSlayer

**Comment by rafmacalaba** [comment]
@ChingSlayer  could you please elaborate how do you execute this trade? any visual representation will do. 

``` Buy when Price > 20 ema > 50 ema > 100 ema AND StochasticRSI is oversold ```

**Comment by enzoampil** [comment]
@rafmacalaba yeah thought so far is to generalize this feature as a `MultiStrategy` feature where users can choose combinations of our library of strategies, and from their set parameters as they wish for multiple strategies :)

**Comment by lorenzourera** [comment]
> Feature Suggestion
> 
> * A backtest/trade strategy which incorporates multiple indicators
> 
> Example:
> 
> * Buy when Price > 20 ema > 50 ema > 100 ema AND StochasticRSI is oversold
> * Sell when close is below 20 ema
> 
> Position Size/Risk Mgt:
> 
> * Risk 2% of portfolio every trade

StochasticRSI isn't part of backtrader. We will need to define this as a custom indicator.

**Comment by ChingSlayer** [comment]
I dont have a specific name for the setup. Here is how I imagine the trade
to look like

**Comment by rafmacalaba** [comment]
> > Feature Suggestion
> > 
> > * A backtest/trade strategy which incorporates multiple indicators
> > 
> > Example:
> > 
> > * Buy when Price > 20 ema > 50 ema > 100 ema AND StochasticRSI is oversold
> > * Sell when close is below 20 ema
> > 
> > Position Size/Risk Mgt:
> > 
> > * Risk 2% of portfolio every trade
> 
> StochasticRSI isn't part of backtrader. We will need to define this as a custom indicator.

https://www.backtrader.com/recipes/indicators/stochrsi/stochrsi/ official docs
https://community.backtrader.com/topic/1652/stochastic-rsi-indicator request

**Comment by rafmacalaba** [comment]
@ChingSlayer I'm afraid you haven't uploaded your attachment

**Comment by lorenzourera** [comment]
> > > Feature Suggestion
> > > 
> > > * A backtest/trade strategy which incorporates multiple indicators
> > > 
> > > Example:
> > > 
> > > * Buy when Price > 20 ema > 50 ema > 100 ema AND StochasticRSI is oversold
> > > * Sell when close is below 20 ema
> > > 
> > > Position Size/Risk Mgt:
> > > 
> > > * Risk 2% of portfolio every trade
> > 
> > 
> > StochasticRSI isn't part of backtrader. We will need to define this as a custom indicator.
> 
> https://www.backtrader.com/recipes/indicators/stochrsi/stochrsi/ official docs
> https://community.backtrader.com/topic/1652/stochastic-rsi-indicator request

got it. thanks!

**Comment by ChingSlayer** [comment]
![AOTS](https://user-images.githubusercontent.com/57378256/83962097-c7f8fd80-a8cc-11ea-8b92-e1eba4a0202e.jpg)

**Comment by ChingSlayer** [comment]
Here is the visual representation/sample :)

**Comment by rafmacalaba** [comment]
@ChingSlayer Thanks for this, however the image is somehow blurry. Just by looking at it, the 50 and 100 ema doesn't seem to have use in the entire strategy or am I missing something?

**Comment by enzoampil** [comment]
A `MultiStrategy` approach like the one below will do the trick:

```
sma = SimpleMovingAverageCrossover(params)
macd = MACDCrossover(params)
multi_strat = MultiStrategy( strategies=[sma,macd], join='or')
```

This is based on the suggestion by @jbdelmundo :smile:

**Comment by enzoampil** [comment]
From the `backtest` function standpoint, I'm thinking something like:

```
strats = {
    "smac": {"fast_period": 15, "slow_period": 40},
    "rsi": {"rsi_lower": 15, "rsi_upper": 70}
}

backtest("multi", df, strats=strats)

```

**Comment by rafmacalaba** [comment]
looks promising! @enzoampil

**Comment by enzoampil** [comment]
Most promising reference I found so far:

Initial idea is to run multiple strategies while instantiating a final one which keeps track of each one with a global dict.

https://community.backtrader.com/topic/1337/running-multiple-strategies-combining-the-output/3

**Comment by enzoampil** [comment]
fitbit api fields

https://dev.fitbit.com/build/reference/web-api/explore/

**Comment by enzoampil** [comment]
Will close this issue since we've already integrated multi-strategy support
