### ISSUE TITLE
Getting started guide to fastquant

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#125]

**Comment by jgendrinal** [comment]
The way this link from the other issue did it might be a good starting point for our guide. 
https://algotrading101.com/learn/backtrader-for-backtesting/

The guide has a limitation that the people reading it are expected to know trading and trading terminology. It would be helpful (even for me personally) if our guide defined terms along the way.

**Comment by jbdelmundo** [comment]
So far, I've identified the following items

- Installation
- Downloading data
- Backtesting using built-in strategies
- Accessing indicators
- Creating custom strategies
- Creating indicators

**Comment by jgendrinal** [comment]
@enzoampil @jbdelmundo should I delete this in favor of #24?

**Comment by enzoampil** [comment]
go for it!

**Comment by jgendrinal** [comment]
Closing this out in favor of #24
