### ISSUE TITLE
[FEATURE] Get available stock ticker symbols

### ISSUE THREAD

**Issue by jgendrinal** [enzoampil/fastquant#126]
Users should be able to call for an exhaustive list of all available ticker symbols on fastquant with one function

**Comment by jgendrinal** [comment]
http://phisix-api.appspot.com/stocks.json

**Comment by dennislwm** [comment]
can i take this one?

**Comment by enzoampil** [comment]
@dennislwm Sure thing! Although, I'd focusing on the list from [Yahoo finance](https://finance.yahoo.com/) first :smile:

**Comment by dennislwm** [comment]
I will do the pse first, yahoo finance seems daunting. What approach would you suggest for Yahoo?

**Comment by enzoampil** [comment]
@dennislwm Merged PSE thanks! For Yahoo Finance, I believe this [resource](https://quant.stackexchange.com/questions/26162/where-can-i-get-a-list-of-all-yahoo-finance-stocks-symbols) looks like it can give guidance.
