### ISSUE TITLE
[FEATURE] Restrict calls to ticker symbols that have an existing stock

### ISSUE THREAD

**Issue by jgendrinal** [enzoampil/fastquant#127]
Users should only be able to call data with ticker symbols that are available on the PSE or another exchange

**Comment by jpdeleon** [comment]
I use [stock_table.csv](https://github.com/enzoampil/fastquant/blob/master/python/fastquant/data/stock_table.csv) as reference of list of stocks when I'm updating data cache using [update_cache](https://github.com/enzoampil/fastquant/blob/master/python/scripts/update_cache) script.

But there are newly listed companies in PSE so it's better to get an updated list.

**Comment by jgendrinal** [comment]
Weird that phisix doesn't have this yet.

**Comment by jgendrinal** [comment]
Will use this to restrict stock calls for phisix -- http://phisix-api.appspot.com/stocks.json

**Comment by enzoampil** [comment]
Good call

**Comment by jgendrinal** [comment]
Kill this. This is what errors are for
