### ISSUE TITLE
R support for fastquant

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#13]

**Comment by jgendrinal** [comment]
Will only close this issue after the first release of the R package

**Comment by jgendrinal** [comment]
- [ ] Ensure that R and Python packages have the same features and tests
- [ ] Both R and Python packages build and pass all tests
- [ ] R package has an approved CRAN submission

**Comment by jgendrinal** [comment]
Closing this issue, as this is an old duplicate of https://github.com/enzoampil/fastquant/issues/120
