### ISSUE TITLE
Sync fastquant notebooks to fastquant-blog w/ Github Actions

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#146]
Guidance can be found [here](https://github.com/fastai/fastpages/issues/357)

**Comment by jpdeleon** [comment]
Similar to #80 .

**Comment by enzoampil** [comment]
I've decided that we don't necessarily have to automate the transfer since it's very possible that there are notebooks that are very useful but not yet exactly "blog posts". Moving forward, I'm in favor of manually curating notebooks and converting them to blog posts as is necessary or preferred by the authors.

Will close this issue.
