### ISSUE TITLE
[BUG] Long queries using get_pse_data returning incomplete OHLCV values

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#157]
This issue is based on this [response](https://medium.com/@eecanabal/this-article-is-great-cc7b8990fc13) to the fastquant blog post on [Medium](https://towardsdatascience.com/access-philippine-stock-data-with-only-2-lines-of-python-309780382b8d?source=friends_link&sk=d4eab964eae7407a62690e4be1c165d7).

Hi Lorenzo!
I used the codes below:
```
from fastquant import get_pse_data
df = get_pse_data("JFC", "2000-01-01", "2020-07-29")
print(df.head())
```
Output:
```
open high low close value volume
dt
2010-01-04 55.5 55.5 55.0 55.5 14598650.0 NaN
2010-01-05 55.5 59.0 55.5 59.0 99016300.0 NaN
2010-01-06 59.0 59.0 58.5 59.0 25933550.0 NaN
2010-01-07 59.0 59.0 59.0 59.0 23334500.0 NaN
2010-01-08 59.5 59.5 59.0 59.0 12325150.0 NaN
```
For the "tail":
```
from fastquant import get_pse_data
df = get_pse_data("JFC", "2000-01-01", "2020-07-29")
print(df.tail())
---------------------------------------------------
Output:
---------------------------------------------------
open high low close value volume
dt
2020-07-22 NaN NaN NaN 130.0 NaN 751080.0
2020-07-23 NaN NaN NaN 126.6 NaN 1364330.0
2020-07-24 NaN NaN NaN 128.5 NaN 400400.0
2020-07-27 NaN NaN NaN 128.0 NaN 653170.0
2020-07-28 NaN NaN NaN 129.1 NaN 1161930.0
```
This is another code i found in github
CODE: get_pse_data_cache()
```
from fastquant import get_pse_data_cache, get_pse_data
df = get_pse_data_cache()
df.tail()
```

The "get_pse_data" was able to pull out the latest closing value (2020-07-28 as of this writing) and date only. However, the complete OHLCV value is only until 2020-04-30 (get_pse_data_cache df.tail). Also, though my start date is 2000-01-01, the output was 2010-01-04.

**Comment by enzoampil** [comment]
I realized from looking at our caching approach that this is actually expected behaviour since we seem to cache based on the output of `get_pse_data_old` but do data pulls with `get_pse_data` @jpdeleon . Let's revisit this approach soon to find a methodology that's more comprehensive for people who want to get any format :smile:

**Comment by jpdeleon** [comment]
Sure. I do not completely remember the details of how I wrote it but very open for a more robust implementation.
