### ISSUE TITLE
[FEATURE] Align R and Python to Binance REST API

### ISSUE THREAD

**Issue by jgendrinal** [enzoampil/fastquant#169]
While developing the R package version of fastquant, I encountered the official Binance REST API. Rather than rely on the cctx package for crypto data, we could reduce the dependency bloat on Python by using the official API instead. 

[Link to Binance Official REST API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)
[Link to part of REST API that might be relevant ](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#klinecandlestick-data)

**Comment by jgendrinal** [comment]
Will resolve this in my next PR

**Comment by enzoampil** [comment]
@jgendrinal heads up that recent PR #171 has the crypto exchange support to the top 6 exchanges :smile:

**Comment by jgendrinal** [comment]
@enzoampil will close this issue. Feel like it would be better to connect using REST APIs in R.
