### ISSUE TITLE
[BUG] Multi-strategy

### ISSUE THREAD

**Issue by Leez94** [enzoampil/fastquant#173]
I tried running the multi-strategy feature found in the example below but i encountered an error https://github.com/enzoampil/fastquant/blob/master/examples/2020-05-10-backtest_multi_strategy.ipynb

#### CODE

```python
from fastquant import backtest, get_stock_data
df = get_stock_data("JFC", "2018-01-01", "2019-01-01")

strats = { 
    "smac": {"fast_period": 35, "slow_period": 50}, 
    "rsi": {"rsi_lower": 30, "rsi_upper": 70}
} 
res = backtest("multi", df, strats=strats)
res.shape
# (1, 16)
```

#### ERROR MESSAGE
```
KeyError                     Traceback (most recent call last)
<ipython-input-20-bd6d68f7f8dd> in <module>
      7     "rsi": {"rsi_lower": 30, "rsi_upper": 70}
      8 } 
----> 9 res = backtest("multi", df, strats=strats)
     10 res.shape
     11 # (1, 16)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastquant\strategies.py in backtest(strategy, data, commission, init_cash, data_format, plot, verbose, sort_by, **kwargs)
    563     }
    564     cerebro.optstrategy(
--> 565         STRATEGY_MAPPING[strategy],
    566         init_cash=[init_cash],
    567         transaction_logging=[verbose],

KeyError: 'multi'
```

**Comment by rafmacalaba** [comment]
Hi @Leez94 thanks for sending/posting this bug report.

Have you updated your fastquant package? try running `pip install fastquant --upgrade`

**Comment by enzoampil** [comment]
Thanks @rafmacalaba . @Leez94 Yes, can confirm it works on this colab [notebook](https://colab.research.google.com/drive/1J7EJq4vPar0-7yGWt2MsuZgzMB9OBn_G?usp=sharing) so the upgraded version should work 😄

**Comment by Leez94** [comment]
Hi @rafmacalaba @enzoampil it worked perfectly now. 
I just ran the `pip install fastquant` and I got the error - I guess the upgrade was necessary for the "multi" to work. Thanks!

**Comment by enzoampil** [comment]
Very welcome @Leez94 and thanks for using fastquant :smile:
