### ISSUE TITLE
update portfolio notebook

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#177]
Update portfolio [notebook](https://github.com/enzoampil/fastquant/blob/master/examples/2020-06-20-basic_portfolio.ipynb) to show fastquant's [portfolio class](https://github.com/enzoampil/fastquant/blob/master/python/fastquant/portfolio.py).

**Comment by benjcabalona1029** [comment]
Thanks Jerome. I'll do this + the proper update for the fastquant blog. Thanks!

**Comment by jpdeleon** [comment]
@benjamincabalona1029 you can add this [similar demo](https://portfolio-optimizer.pyviz.demo.anaconda.com/portfolio) in the notebook :)

**Comment by benjcabalona1029** [comment]
@jpdeleon okay. I think this is rendered with Voila?

Btw @enzoampil  should i reorganize the notebook to NOT include the introductory sections? (i.e. quick stock market 101, definition of returns, etc. ) The original audience of my notebook/presentation are not actually "finance" people.

**Comment by jpdeleon** [comment]
@benjamincabalona1029 I do not know but it looks awesome!

**Comment by enzoampil** [comment]
@benjamincabalona1029 I think the introductory sections are GREAT and are a big part of why it's such a great post :smile: Let's keep it!
