### ISSUE TITLE
[FEATURE] How to control the size plots when backtrader plots are embedded into notebook output

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#202]
Currently, it's common to have workflows where backtrader plots are rendered straight from a jupyter or colab notebook. The issue is that the size of the plot is quite small by default, which makes it difficult to see through the busy contents of the backtesting results.

 It would be great if `backtest` could have a `figsize` argument similar to `matplotlib.pyplot`, where the default is much bigger than the current setup. E.g. `figsize=(12, 7)` could be a good default.

**Comment by enzoampil** [comment]
Sample default size:

![image](https://user-images.githubusercontent.com/39557688/90148298-c4df2980-ddb5-11ea-9166-76305fcde6f4.png)

**Comment by jpdeleon** [comment]
I looked into this problem and found a solution below.
We just need to add these lines on top of the jupyter notebook.
```python
import matplotlib.pyplot as pl
pl.style.use("default") #ggplot is also fine
pl.rcParams["figure.figsize"] = (15,12)
#all styles: print(pl.style.available)
```
Documentation: https://matplotlib.org/3.3.0/tutorials/introductory/customizing.html
We may be able to set this global config automatically if code is being run in jupyter but there may be [caveats](https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook).

**Comment by enzoampil** [comment]
Understand @jpdeleon . Thanks will use this as quick fix. I think this should be automated as much as possible straight from `backtest`.

Yeah, think it makes sense to start chipping away at these plotting issues. Really affects the UX of the tool.

**Comment by enzoampil** [comment]
Also, great to refer these two relevant threads on backtrader docs: [link1](https://community.backtrader.com/topic/291/ipython-notebook-plot-sizing/5), [link2](https://community.backtrader.com/topic/22/plot-maximize-windows/2)

**Comment by jbdelmundo** [comment]
I added support for `figsize()` parameter in the `backtest` function in https://github.com/enzoampil/fastquant/pull/286/files#diff-9081e26fa869af389e67c6f9e0872cb6eb190052979673832a9b2f4a6215343eR67

**Comment by enzoampil** [comment]
Thanks @jbdelmundo ! :smile:
