### ISSUE TITLE
[FEATURE] Add super quiet logging, for manageable outputs when using grid search

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#203]
The default logging when verbose is `False` is still quite verbose, yet still very much useful for a lot of cases. I propose to add a new setup where verbose is an integer, indicating different levels of verbosity.

`verbose=0` should be  minimal, returning only the final portfolio value, PnL, and optimal results & parameters. `verbose=-1` will print absolutely nothing!

Levels -1 and 0 will be a much better experience for users on notebooks and ipython, or pretty much anyone who makes heavy use of our grid search functionality.

The default behavior (currently `verbose=False`) will be `verbose=1`, and the prior `verbose=True`, will be `verbose=2`.

I.e., the argument `verbose` can take values: `[-1, 0, 1, 2]`, with increasing levels of verbosity.

**Comment by rafmacalaba** [comment]
self-assigning this.

**Comment by jbdelmundo** [comment]
I asked permission from @rafmacalaba to assign to me

Currently planning to have different levels
0 - no output
1 - Strategy level: strat parameters, Final PNL, Strategy Summary
2 - Transaction level: All transactions
3 - Periodic Logging:  For every row in the data
