### ISSUE TITLE
Add cash during run?

### ISSUE THREAD

**Issue by leobaumgardt** [enzoampil/fastquant#215]
How can I add cash every month during backtesting?

I'd like to backtest a strategy that looks like this:

1. Every month, another $1,000 is added in cash. Say, surplus from my salary. Let's call this "income".
2. While the algorithm does not buy any more stock, my income accumulates.
3. Once tha algorithm decides to buy stock, it will use...
a) all of the available cash on hand.
b) a pre-determined percentage of the cash on hand.
4. The algorithm never sells any stock (I think I can do that by setting upper_limit=999).

**Comment by enzoampil** [comment]
@leobaumgardt thanks for using fastquant!

1. We don't have an `income` feature yet, but we can add this as a feature request. Top of mind, you can set an "income" amount, with a specified "fequency".
2. Same as 1
3. You can already set the proportion of your cash that you use to buy. This is set with the `buy_prop` parameter in `backtest`, which is set to 1 (100%), by default.
4. Makes sense, you can already do this with the `buynhold` strategy (just buy and hold the asset).

Hence, the only missing feature from your description is the `income` feature that allows you to simulate getting periodic cash, from an external source. We can add this to the feature backlog :smile:

For now, I think the [buynhold](https://github.com/enzoampil/fastquant#library-of-trading-strategies) strategy is the closest to what you want to be using :grin:

**Comment by leobaumgardt** [comment]
Thank you!
