### ISSUE TITLE
[FEATURE] MINUTE based custom strategy 

### ISSUE THREAD

**Issue by prasanth-m** [enzoampil/fastquant#234]
As sample custom strategy with 1 min data to build and test 5 min or 10 min time frame based systems using previous or highest peak of current day as target and previous or lowest trough day as stop loss for long and vice versa for short with number of peaks and trough to trace back as params in grid search.

**Comment by enzoampil** [comment]
This makes sense @prasanth-m . I'm just wondering, what's the buy signal for this strategy?

**Comment by prasanth-m** [comment]
@enzoampil As like stop loss and target , we will go the dynamic entries.
1) Buy when two of most recent peak is broken.
2) Sell when two of most recent trough is broken.

**Comment by enzoampil** [comment]
Minute level data should already be possible to use with `backtest`
