### ISSUE TITLE
[FEATURE] Make yahoo finance the default for get_stock_data

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#235]
With our new direction of prioritizing more generally usable features, I think it makes sense to make `get_stock_data` default to yahoo finance instead of pse. So make the logic so that if the ticker is not detected in yahoo finance, only then does it query for PSE.

Also, given this change, I think the best format would be the standard `OHLCV`. If it resorts to `phisix` we just bring it back to `C` format.

cc @jpdeleon @jgendrinal in case you have thoughts on this

**Comment by rafmacalaba** [comment]
I'm taking this.
