### ISSUE TITLE
[FEATURE] Shorting support

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#236]
Currently fastquant only support long position trades. Forex use cases will definitely need shorting, and we'll need a separate handling for closing short and long positions

**Comment by jgendrinal** [comment]
I'll take a stab at this next

**Comment by enzoampil** [comment]
Let's pair on this @jgendrinal . There will be a lot of implications on this side haha

**Comment by jgendrinal** [comment]
You've probably seen [this example](https://www.backtrader.com/blog/posts/2016-12-06-shorting-cash/shorting-cash/) for SMAC already. Let me know if I'm on the right track

**Comment by enzoampil** [comment]
@jgendrinal looks good! Actually the key to implementing shorting support is in relaxing some of the constraints in `BaseStrategy`. Currently we only trigger a sell order when `stock_value > 0`. I.e., shorting is not allowed (reference [line](https://github.com/enzoampil/fastquant/blob/b87e3a057594c607ff5107a18bce8e7d4f074efb/python/fastquant/strategies/base.py#L292)).

Theoretically, we can just relax this constraint and shorting should then be allowed. My recommendation is to add a parameter indicating if shorting is allowed, which is set to False by default. E.g. `long_only=True`. If shorting is allowed, then we can relax the constraint above :smile:

Lemme know if you want any more clarification here! 😁

**Comment by jgendrinal** [comment]
@enzoampil Expect my PR this week!

**Comment by jgendrinal** [comment]
Also, I'll implement stop loss and stop trail for short selling in a future PR
