### ISSUE TITLE
Initialize documentation website

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#24]
https://www.sphinx-doc.org/en/master/

**Comment by jpdeleon** [comment]
Try [just-the-docs](https://pmarsceill.github.io/just-the-docs/) as a simpler documentation framework alternative

**Comment by enzoampil** [comment]
Thanks, will look through these today an initialize a V0

**Comment by enzoampil** [comment]
@jpdeleon Thanks for this. I agree that it makes sense to use github pages (V0 [here](https://enzoampil.github.io/fastquant/)).

**Question:** Is there a specific reason why we would want the website's source code to live in a separate branch (`gh-pages`)? Is it so `master` doesn't get cluttered with docs?

**Comment by jpdeleon** [comment]
> **Question:** Is there a specific reason why we would want the website's source code to live in a separate branch (`gh-pages`)? Is it so `master` doesn't get cluttered with docs?

I don't have a reason for keeping docs as a separate branch except because that's what is demonstrated on gh-pages. My previous issue with it was I had to always merge master (ahead of docs) every time and resolving conflicts is a bottleneck. Traditionally, documentation lives in master i.e. as /docs, so I am OK if we develop it alongside master.

**Comment by enzoampil** [comment]
Thanks for clarifying. Yep, my thought is to make it live in master so we don't have to resolve bottlenecks.

**Comment by enzoampil** [comment]
Revisiting this issue as our features are getting more and more complex and we'll need more detailed docs. @jpdeleon I'm reassessing whether to use sphinx vs github-pages for our docs. What I like about sphinx is that we can auto-generate the docs by updating docstrings. Would you be able to elaborate on why github-pages would be easier to maintain? :smile:

**Comment by enzoampil** [comment]
@jgendrinal proposing to use docusaurus :smile I'm okay giving you full creative freedom here. Choose the platform you want!

**Comment by jgendrinal** [comment]
https://docusaurus.io/en/

**Comment by jgendrinal** [comment]
Will make a new draft PR for this

**Comment by jgendrinal** [comment]
New fastquant-org/fastquant-doc repo!
