### ISSUE TITLE
[BUG] extra columns in backtest output

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#248]
`channel` and `symbol` columns still show up in metrics_df output from `backtest`

**Comment by dennislwm** [comment]
hi,
can i take this one?

**Comment by enzoampil** [comment]
@dennislwm Yes, you definitely can! To fix this, you just have to exclude the `channel` and `symbol` columns in the `metrics_df` dataframe (this [line](https://github.com/enzoampil/fastquant/blob/48d32bd5ab255892ac076b3db9198a753721c2a3/python/fastquant/backtest/backtest.py#L350)) and send over a PR!

Contribution guide [here](https://github.com/enzoampil/fastquant/blob/master/CONTRIBUTING.md#get-started).

Do let me know if you need any assistance with this, always happy to help :smile:

**Comment by dennislwm** [comment]
Thank you. Could you share the code that reproduces the above dataframe?

**Comment by enzoampil** [comment]
@dennislwm  You can test it out yourself by running the backtest function, which will have multiple rows when you use multiple argument inputs :smile:

```
from fastquant import get_crypto_data, backtest
df = get_crypto_data("BTC/USDT", "2018-12-01", "2019-12-31")
metrics_df = backtest('smac', df, fast_period=[10, 15, 20], slow_period=40)

print(metrics_df.head())
```
