### ISSUE TITLE
Intraday data?

### ISSUE THREAD

**Issue by alexgorbachev** [enzoampil/fastquant#252]
Does Fastquant support intraday data? Not download but to bring my own.

**Comment by jpdeleon** [comment]
Hi @alexgorbachev 
Yes, fastquant works with intra-day data.
If you feed your data to `backtest` for example, make sure it is a pandas dataframe with appropriate column names like this [file](https://github.com/enzoampil/fastquant/blob/master/python/fastquant/data/JFC_2010-01-01_2019-01-01_OHLCV.csv).
