### ISSUE TITLE
[BUG] SharpeRatio analyzer only returning None

### ISSUE THREAD

**Issue by ghost** [enzoampil/fastquant#257]
SharpeRatio timeframe parameter default is in TimeFrame.Year. Because our data does not cover several years, we are unable to produce a Sharpe Ratio. 

Task is to change timeframe without breaking the whole backtest.py module. 

Raised in PR #256

**Comment by mikeejazmines** [comment]
Closing as this is connected to https://github.com/enzoampil/fastquant/pull/256
