### ISSUE TITLE
PositionIndicatorStrategy 

### ISSUE THREAD

**Issue by jbdelmundo** [enzoampil/fastquant#261]
I come across this research paper long time ago that uses "position" indicators as signals on what to do in a market.

An additional "Strategy" that includes a column "position" which have values [1,0,-1] that is equivalent to [long/buy, neutral, short/sell]

For example:
The "position" column has 7 values for 7 days:  `[0,1,1,0,0,-1,-1,0]`
What it means is:

- Day 1: No action
- Day 2: Buy (Go to long position)
- Day 3: No action (keep the long position)
- Day 4: Sell (Go to neutral position)
- Day 5: No action (keep the position at neutral)
- Day 6: Short sell (Go to short position)
- Day 7: No action (keep short position)
- Day 8: Buy (Go to neutral position)

This is mostly used in markets where you could do short selling like forex

The `TernaryStrategy` could be modified to adopt to this once short selling is supported

**Comment by enzoampil** [comment]
Agree, this should basically be `TernaryStrategy` once we add short selling support :smile:

**Comment by enzoampil** [comment]
@jbdelmundo Now that we have short selling support, this can be done with `TernaryStrategy`. Just make sure to set `allow_short=True` when running `backtest`.

More details in this [PR](https://github.com/enzoampil/fastquant/pull/262).

I'll close this issue now that this is possible :grin:
