### ISSUE TITLE
[BUG] get_twitter_sentiment() fails because datetime and pd not defined in fastquant/data/web/twitter.py

### ISSUE THREAD

**Issue by jgarifuna** [enzoampil/fastquant#270]
#### Problem description

When running **get_twitter_sentiment()** from **fastquant/data/web/twitter.py** the operation fails for the following two reasons:

name '**datetime**' is not defined
-- this happens on line 61: new_tweets = [tweet for tweet in item if datetime.strptime(str(

name '**pd**' is not defined
-- this happens on line 79: tweet_df = pd.DataFrame([])

#### Example

```python
import fastquant.data.web.twitter as ttr
from fastquant import backtest, get_yahoo_data
from datetime import datetime, timedelta

# we get the current date and delta time of 30 days
stock_symbol = "TSLA"

current_date = datetime.now().strftime("%Y-%m-%d")
delta_date = (datetime.now() - timedelta(30)).strftime("%Y-%m-%d")
data = get_yahoo_data(stock_symbol, delta_date, current_date)


consumer_key = 'put_your_API_key_here'
consumer_secret = 'put_your_API_secret_key_here'
access_token = 'put_your_access_token_here'
access_secret = 'put_your_access_token_secret_here'

twitter_api = ttr.tweepy_api(consumer_key, consumer_secret, access_token, access_secret)

stock_name = "tesla"
twitter_accounts = ['vincent13031925']

sentiments = ttr.get_twitter_sentiment(stock_code=stock_name, twitter_auth=twitter_api, start_date=delta_date, twitter_accounts=twitter_accounts)

# set plot size
import matplotlib.pyplot as pl
pl.style.use("default") #ggplot is also fine
pl.rcParams["figure.figsize"] = (8,10)

backtest("sentiment", data, sentiments=sentiments, senti=0.2)

```

#### Expected behavior

For get_twitter_sentiment() to finish successfully, so I can perform backtest. 

Based on my investigation, adding the following at the top of "**fastquant/data/web/twitter.py**" could fix the issue(or at least it fixed it for me):

**added by Jorge Garifuna on 10/21/20 to eliminate error on line 61: new_tweets = [tweet for tweet in item if datetime.strptime(str(**
```
from datetime import datetime
```
**added by Jorge Garifuna on 10/21/20 to eliminate error on line 79: tweet_df = pd.DataFrame([])**
```
import pandas as pd
```

#### Environment

-  platform (OSX):
-  fastquant version (0.1.3.23)
-  installation method (pip
![bug_twitter_pd_not_defined_102220](https://user-images.githubusercontent.com/1472303/96908483-8fa82500-1451-11eb-89ce-16c2ada5eb15.png)
![bug_twitter_datetime_not_defined_102220](https://user-images.githubusercontent.com/1472303/96908487-90d95200-1451-11eb-9912-82158c888772.png)

):

**Comment by enzoampil** [comment]
@jgarifuna thanks for this. Would you mind sending a PR for this change small change? Would be great to have you as a contributor 😀
