### ISSUE TITLE
Refactor Backtest Function into components

### ISSUE THREAD

**Issue by jbdelmundo** [enzoampil/fastquant#285]
Refactor the `backtest()` function into smaller logical parts. This will allow us to manage further changes to each component

- Data Preprocessing (Handling of CSVs, columns, data formats etc)
- Strategy Preparation (strategy parameters, etc)
- Adding Analyzers (Returns, Sharpe, DrawDown, TimeDrawDown)
- Indicators, Transactions, Periodic History
- Plotting

# Note that the `backtest()` function will just call the mentioned components

**Comment by enzoampil** [comment]
Super agree @jbdelmundo . Backtest has grown to be quite unwieldy at this point.

**Comment by jgendrinal** [comment]
:+1:
