### ISSUE TITLE
Getting PSE data

### ISSUE THREAD

**Issue by homerjay88xx** [enzoampil/fastquant#296]
I'm trying to get PSE data but can't really make your code work properly.

When I'm doing:
df = get_stock_data("JFC", "2020-01-01", "2020-11-01")

I get the following error:
1 Failed download:
- JFC: No data found for this date range, symbol may be delisted

If I'm doing:
df = get_pse_data("JFC", "2020-01-01", "2020-11-01")

It takes quite some time to get done and in the end I only have closing prices.
What am I doing wrong?

**Comment by fjbriones** [comment]
I think you explicitly state in get_stock_data that the source should be "phisix" because it seems like the default is yahoo and it does not return None rather it returns an empty data frame so it does not automatically go to get_pse_data.

**Comment by enzoampil** [comment]
Hi thanks for bringing up this issue. This should be pulling via phisix for PH stocks. Will add this to the backlog as a bug.

With regard to just getting closing prices, weve switched to utilising the phisix API for the pricing data and it only includes closing prices.

**Comment by enzoampil** [comment]
@fjbriones In case you're interested, you can send over a PR for a suggested fix :smile: Happy to review and make sure it gets merged! :grin:
