### ISSUE TITLE
[FEATURE] Function to pull company disclosure information in parse-able format

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#31]
Disclosures can be found in PSE edge

https://edge.pse.com.ph/

**Comment by jpdeleon** [comment]
See [disclosures branch](https://github.com/enzoampil/fastquant/tree/disclosures).

TODO:
- [x] refactor functions into a class in disclosures.py   
- [] add time column in details parsed from `get_disclosure_summary`
- [] add tests
- add NLP methods  (or output fed into an NLP class)

**Comment by jpdeleon** [comment]
Fixed by #47
