### ISSUE TITLE
[FEATURE] OHLCV 

### ISSUE THREAD

**Issue by geyseragustin-md** [enzoampil/fastquant#310]
**Is your feature request related to a problem? Please describe.**
Hi is it still possible to get an OHLCV format? 

**Additional context**

**Comment by enzoampil** [comment]
Hey @geyseragustin-md , stocks from yahoo finance, and cctx (crypto) should be full `ohlcv` so far. Are you referring to a stock from PSE?

**Comment by geyseragustin-md** [comment]
Hi Enzo, thank you for your quick response, yes I was referring to the stocks from PSE

**Comment by enzoampil** [comment]
Hi @geyseragustin-md , so fastquant now pulls from the phisix API, which only returns up to closing, and volume data. We can add `hlc` data once this is integrated to `phisix`.

**Comment by rafmacalaba** [comment]
closing this issue since we have a limited amount of data for phisix api. Thanks for using fastquant!
