### ISSUE TITLE
[BUG] Can't install Fastquant

### ISSUE THREAD

**Issue by datomnurdin** [enzoampil/fastquant#335]
#### Problem description
Can't install Fastquant

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX
-  fastquant version (e.g. 0.1.3.17): latest version
-  installation method (e.g. pip, conda, source): pip

I'm getting this error message: https://gist.github.com/datomnurdin/9316fc269c71b4a6ca3f5a947a1c0272

**Comment by rafmacalaba** [comment]
@datomnurdin hello, thanks for using fastquant.

could you install it on a virtual environment and give us the traceback if theres an error :) Thanks!

**Comment by enzoampil** [comment]
I notice these tend to happen for the recent python version ... (e.g. 3.9)

**Comment by enzoampil** [comment]
This should be resolved by this recent [PR](https://github.com/enzoampil/fastquant/pull/345) by @jgendrinal :smile:
