### ISSUE TITLE
[BUG] lower_limit upper_limit doesn't do anything

### ISSUE THREAD

**Issue by thistleknot** [enzoampil/fastquant#353]
working on a proper strategy that only forecasts 1 day ahead using a rolling window

but... after b = ...

I always get the same order book.  Which doesn't make any sense.  I clearly have a buy/sell decision most days (maybe i'm selling when I don't have any stocks?)  well I checked that, that's not the case in fact upper_limit and lower_limit I can inverse the signs and it doesn't have any effect on the final output.  I have a dataframe with a custom variable.  All that's needed is to investigate this part forward.  Not sure what I'm missing.  I was hoping to submit this as a working example of how to do time series forecasting properly with fbprophet (using rolling windows), but when I went to mess with the thresholds... that's when I realized I was getting the same results.  The only time it seems to make a difference is when I use the #.multiply(-1) that I've commented out

```
from fastquant import get_crypto_data, backtest
from fbprophet import Prophet
from matplotlib import pyplot as plt
from fbprophet.diagnostics import cross_validation
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

outter_df = get_crypto_data("BTC/USDT", "2019-01-01", "2020-05-31")

#1 year and 1 quarter
oneyroneqtr=456
length = len(outter_df[0:oneyroneqttr])

custompre = pd.DataFrame()

column_names = ["date", "yhat"]

#ustompre = pd.DataFrame(columns = column_names)

def MAPE(Y_actual,Y_Predicted):
    mape_ = np.mean(np.abs((Y_actual - Y_Predicted)/Y_actual))*100
    return mape_

for x in range(0,len(outter_df)):
    frames = outter_df.index[x:(x+oneyroneqttr)]
    length = len(frames)
    if length == oneyroneqtr:
        #print(outter_df.loc[frames])
        
        df = outter_df.loc[frames]
        
        ts = df.reset_index()[["dt", "close"]]
        ts.columns = ['ds', 'y']

        #strips last day from model
        m = Prophet(daily_seasonality=True,yearly_seasonality=True)
        m.add_seasonality(name='monthly', period=30.5, fourier_order=5)
        m.add_seasonality(name='quarterly', period=91.25, fourier_order=7)
        m.fit(ts[0:-1])

        #forecast only last day in model (can verify result)
        forecast = pd.DataFrame(df.index)[-1:]
        forecast.columns = ['ds']
        

        #Predict and plot
        pred = m.predict(forecast)
        
        temp = pd.DataFrame()
        #print(pred)
        #print(pred['yhat'].values[0])
        temp['date'] = frames[-1:].strftime('%Y-%m-%d')
        temp['yhat'] = pred['yhat']
        custompre = custompre.append(temp, ignore_index=True)
        
    else:
        break
        
# Convert predictions to expected 1 day returns
custom = custompre
custom.columns = ["dt","yhat"]

merge=pd.merge(outter_df,custom.set_index('dt'), how='inner', left_index=True, right_index=True)
expected_1day_return = ((merge['yhat']-merge['close'])/merge['close']).multiply(100)

df = merge
df["custom"] = expected_1day_return
#.multiply(-1)

# Backtest the predictions, given that we buy bitcoin when the predicted next day return is > +1.5%, and sell when it's < -1.5%.
b = backtest("custom", df.dropna(),upper_limit=.75, lower_limit=-.75, return_history=True)
#, buy_prop=0.10, sell_prop=1,commission=0.01, init_cash=1000)

price_data = merge["close"]
#print(price_data)

values = b[1]['periodic']['portfolio_value']
#print(len(values))
ret_value = values.pct_change()[1:]
cumulative_ret_value = (ret_value + 1).cumprod()

og_ret_data = price_data.pct_change()

#og_merge = pd.merge(df,custom.set_index('dt'), how='inner', left_index=True, right_index=True)
cumulative_og_ret_data = (og_ret_data + 1).cumprod()

#cumulative_og_ret_data.reset_index()
cumulative_og_ret_data.reset_index(drop=True, inplace=True)
#print(cumulative_og_ret_data.index)

plt.plot(cumulative_ret_value)
plt.plot(cumulative_og_ret_data)

print(cumulative_ret_value[-1:].values[0])
print(cumulative_og_ret_data[-1:].values[0])

metrics = pd.DataFrame()
metrics['close'] = merge['close'].shift(-1)
metrics['yhat'] = merge['yhat']
metrics = metrics.dropna()

rmse = mean_squared_error(metrics['close'], metrics['yhat'], squared=True)
mape = MAPE(metrics['close'], metrics['yhat'])
print(rmse)
print(mape)

```

**Comment by enzoampil** [comment]
@thistleknot I'm not sure if this is the case, but I suspect that it's because the initial cash position is only set to 100K and BTC/USDT has recently shot up to USD 57K. Can you try increasing `init_cash` substantially to say `1000000`?

For context, we don't support "fractional" trades yet, which should be doable with crypto currencies like BTC. To circumvent this for now, we can just set `init_cash` to a sufficiently large number so that it can easily buy BTC in whole units.

Lemme know if results look more sensible after doing the above :smile:

**Comment by thistleknot** [comment]
That just might be it. I didnt even bother to think about the fact it was
in 57k

**Comment by thistleknot** [comment]
same.  I saved the file as a csv and uploaded it here
https://github.com/thistleknot/Python-Stock/blob/master/btresults.csv

**Comment by thistleknot** [comment]
that didn't solve it for me.  I ended up writing my own backtesting function using what I've learned from your orderbook and quanstrat.  Although I don't know if I have it right.

**Comment by thistleknot** [comment]
here's my csv

it looks like I might be getting similar results now with my updated backtest script I wrote
![image](https://user-images.githubusercontent.com/5154106/108635145-4c7fb200-7443-11eb-9ae0-46d406a946f9.png)


vs
![image](https://user-images.githubusercontent.com/5154106/108635142-3d006900-7443-11eb-8acc-55927f8f2153.png)


https://github.com/thistleknot/Python-Stock/blob/master/btresults.csv

So I think i'm just an idiot and didn't have something right...  I did have to adjust my custom columns.

**Comment by enzoampil** [comment]
Is this the data csv, and you're using the full script above?

**Comment by thistleknot** [comment]
I'm saying you can use that csv and try changing values

# Convert predictions to expected 1 day returns
expected_1day_return = pred.set_index("ds").yhat.pct_change().shift(-1).multiply(100)

# Backtest the predictions, given that we buy bitcoin when the predicted next day return is > +1.5%, and sell when it's < -1.5%.
df = pd.read_csv('btresults.csv')
#may be necessary
df = df.set_index('dt')

df["custom"] = expected_1day_return.multiply(-1)
backtest("custom", df.dropna(),upper_limit=1.5, lower_limit=-1.5)

**Comment by enzoampil** [comment]
@thistleknot ah got it. Wait, so with your updated backtest script, does it now seem to be working as expected?

**Comment by thistleknot** [comment]
Sorry i've been off on my own tangent (I wrote my own backtest algorithm
that uses partial trades).

I haven't looked at this since.  You can close the bug out for now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
