### ISSUE TITLE
[FEATURE] - custom strategy: exit strategy different than entry

### ISSUE THREAD

**Issue by 0cv** [enzoampil/fastquant#358]
**Is your feature request related to a problem? Please describe.**
When allow_short is true, entry and exit are blurred (defined by sell_prop and buy_prop

**Describe the solution you'd like**
it shall be possible to specify an entry_long, exit_long, entry_short, exit_short - so that we can stay without any open position on sideway situations.

**Describe alternatives you've considered**
set allow_short to false, then simulate long. Then reverse the data and simulate short as if it was a long (very tedious and error prone)

**Additional context**
Maybe it exists and I missed the feature, if so please let me know

**Comment by enzoampil** [comment]
@0cv Thanks for this feedback! `allow_short`, is a new feature so this seems like a situation we haven't yet built for. I definitely agree it would be useful, and has popped up in conversations to include it!

Will add this to the feature backlog :smile: Feel free to try to implement this as well via a PR, and I would be glad to guide you through the process!

**Comment by mikeejazmines** [comment]
this was resolved in https://github.com/enzoampil/fastquant/pull/404
