### ISSUE TITLE
[BUG] ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by dvdtth** [enzoampil/fastquant#359]
#### Problem description
While using backtest with grid search, getting "ValueError: too many values to unpack (expected 2)"

#### Example

```python
from fastquant import backtest, get_stock_data
df = get_stock_data("JFC", "2018-01-01", "2019-01-01")
res = backtest("smac", df, fast_period=range(15, 30, 3), slow_period=range(40, 55, 3), verbose=False)
```

#### Expected behavior
Code above runs to completion without errors

#### Environment
-  platform= Windows 10
-  fastquant version0.1.4.0
-  installation method = pip
- Python version = 3.9.2
- matplotlib version = 3.2.2

**Comment by enzoampil** [comment]
@dvdtth Can you please post the full error message?

Thanks for using fastquant :smile:

**Comment by rafmacalaba** [comment]
@enzoampil this is a bug with grid search. I experienced it also. I'll take this

**Comment by dvdtth** [comment]
Thanks for the fix. The error "too many values to unpack" is now gone.

However, a new error shows up now. 
"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

Seems to be failing somewhere in backtrader, but not sure whether that's due to something pass to it through fastquant?

image](https://user-images.githubusercontent.com/2410499/115946510-431ece80-a4f4-11eb-8711-f22db5e14375.png)

* using backtrader 1.9.76.123 btw
