### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ddfire** [enzoampil/fastquant#360]
#### Problem description
can not bring info from others exchange except binance
i tried differents ways to put the ticker, 

for example this works https://api.kraken.com/0/public/OHLC?pair=XDGUSD 
this works crypto2 = get_crypto_data("DOGE/USDT", "2021-03-02", "2021-03-03",'5m') #binance
but for kraken does not work, i tried XDGUSD as ticker, also does not work

Thanks!!! 

#### Example

```python
from fastquant import get_crypto_data
crypto2 = get_crypto_data("DOGE/USDT", "2021-03-02", "2021-03-03",'5m','kraken')
print("kraken")
print(crypto2)
```
result: 
Traceback (most recent call last):
  File "coin1.py", line 7, in <module>
    crypto2 = get_crypto_data("DOGE/USDT", "2021-03-02", "2021-03-03",'5m','kraken')
  File "/Users/davidfaerman/opt/anaconda3/lib/python3.8/site-packages/fastquant/data/crypto/crypto.py", line 44, in get_crypto_data
    ohlcv_lol = ex.fetch_ohlcv(ticker, time_resolution, since=start_date_epoch)
  File "/Users/davidfaerman/opt/anaconda3/lib/python3.8/site-packages/ccxt/kraken.py", line 615, in fetch_ohlcv
    market = self.market(symbol)
  File "/Users/davidfaerman/opt/anaconda3/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1826, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: kraken does not have market symbol DOGE/USDT

#### Expected behavior
bring the data
#### Environment
OSX
latest
pip

**Comment by mikeejazmines** [comment]
Hi! This issue is mainly due to how you call the symbols. Binance uses DOGE/USDT but Kraken at the time of your issue, used DOGE/USD. They did allow DOGE/USDT at April so this should be good too!
