### ISSUE TITLE
[BUG] The grid search breaks when attempting to plot the result using the optimal parameters

### ISSUE THREAD

**Issue by dbeis** [enzoampil/fastquant#367]
#### Problem description
The grid search breaks when attempting to plot the result using the best parameters

#### Example

```python
import fastquant
import pandas as pd

test = pd.DataFrame([[1,0.1,'11-02-2021'],[3,0.2,'12-02-2021'], [4,0.4,'13-02-2021'], [5, 0.1,'14-02-2021']], columns=['close', 'custom', 'datetime'])
res = fastquant.backtest('custom', test, upper_limit=[1,2,3], lower_limit=[4,5,6], verbose=False)
```

#### Expected behavior
The code breaks while ploting the best params result with the following error:
```
d(self, cash, value, fundvalue, shares)
     91         if not self._fundmode:
     92             self._value = value  # record current value
---> 93             self._maxvalue = max(self._maxvalue, value)  # update peak value
     94         else:
     95             self._value = fundvalue  # record current value

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
#### Environment

-  Ubuntu 20.04
-  fastquant @ git+https://github.com/enzoampil/fastquant.git@de7e381bb56848889a1d20b6424b81c72cb3172d
-  pip pulls it from gitlab

**Comment by jpdeleon** [comment]
Hi @dbeis thanks for using fastquant.

The grid search does not work for backtesting `custom` indicators so `upper_limit` and `upper_limit` parameters cannot accept arrays, but only floats instead.

**Comment by mikeejazmines** [comment]
Hi @dbeis similar issue to https://github.com/enzoampil/fastquant/issues/393

Plotting does not work with upper_limit and lower_limit. The code will run if you add `plot=False`

Another way is to run the backtest and get the best params and then input only the best params to another backtest function for plotting as what jp mentioned.
