### ISSUE TITLE
No tracebility for pip packages

### ISSUE THREAD

**Issue by Enforcer007** [enzoampil/fastquant#375]
Hi @enzoampil ,

The current latest pkg version in pip is "1.4.0", where as in the github the dev branch version is 1.3.* (from setup.py)

I'm unable to see a release package/branch in this repo for pip. 

Can you help me out in this regards.

**Comment by enzoampil** [comment]
Hi @Enforcer007 - apologies we haven't updated pip yet. If your run setup.py on master that should be the latest version :smile: But will update the pip package in the next week or so!

**Comment by Enforcer007** [comment]
Thanks for the clarification. 🤝

**Comment by Enforcer007** [comment]
I also observed there's an issue in rendering the chart. I'll raise a new issue for it.

**Comment by Enforcer007** [comment]
Already there was an issue created same to what I faced - https://github.com/enzoampil/fastquant/issues/369
