### ISSUE TITLE
[BUG] Missing Data for some dates

### ISSUE THREAD

**Issue by ShawnKenley** [enzoampil/fastquant#379]
#### Problem description

Opening Prices, Highs, Lows only show up for dates August 03, 2020 and earlier while Volume is Null for said dates. Only Closing Prices, Volume, and Dividends show up for dates August 04, 2020 and Later.

#### Example

```python
from fastquant import get_pse_data
df = get_pse_data("ALI", '2020-7-20', '2020-9-30')
print(df)
```

#### Expected behavior

Opening Prices, Highs, Lows, Closing, Value, Volume and Dividends all show up for all dates.

#### Environment

-  platform (OSX):
-  fastquant version (0.1.5.0)
-  installation method (pip):

**Comment by mikeejazmines** [comment]
Hi! This is mainly an issue with the data provider and not the get_pse_data function. This is because the function mainly pulls and aggregates from `PHISIX` through `get_phisix_data`

Note that PSE data in general isn't as clean as other assets as the data isn't as openly accessible.
