### ISSUE TITLE
Not able to optimize the stop loss and other floating parameters.

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#401]
![issue](https://user-images.githubusercontent.com/74678250/146574297-4ffc8451-1c9c-45eb-bcb9-e4417ac8e312.PNG)

**Comment by mikeejazmines** [comment]
Hi! Could you share more of the code? I can't fully analyze the issue.

Looking at the error message, it is mainly due to you using floats instead of integer which is what the value expects. It isn't due to stop loss or floating params.

**Comment by YASHGUPTA2611** [comment]
![1](https://user-images.githubusercontent.com/74678250/146637876-0e58816c-1f15-4413-9dd7-7aa1c75578d2.PNG)
![2](https://user-images.githubusercontent.com/74678250/146637882-ececfdf9-99cd-468e-b35d-8b4aa5dde27e.PNG)

I have applied a range function(the circled one) on af params for optimizing my strategy but it is giving some error.

**Comment by mikeejazmines** [comment]
If you see the error below it says `TypeError: float object cannot be interpreted as an integer`. If you run `range(0.02, 0.1, 0.02)` it actually gives an error.

```
>>> range(0.02, 0.1, 0.02)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

This is an error in the range function. You can also manually add an array instead.

**Comment by YASHGUPTA2611** [comment]
![1](https://user-images.githubusercontent.com/74678250/146647599-9f8ea79c-3484-493d-97e7-75a6f843ca44.PNG)
![2](https://user-images.githubusercontent.com/74678250/146647602-a9753b29-83bb-4c5f-b7fb-a5822a1b58c3.PNG)
![3](https://user-images.githubusercontent.com/74678250/146647603-3ad5fe92-c1ce-4274-953b-a63d73be9cc9.PNG)
giving the values as an array and now it is giving the error : -
**ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()**

**Comment by mikeejazmines** [comment]
This is the same issue as what you raised previously in this issue https://github.com/enzoampil/fastquant/issues/393#issuecomment-993367593

When you are backtesting with a range, you need to make the value of plot=False. That ValueError means that there are too many values to plot (given that you are backtesting over a range) and it is ambiguous. Thus `plot=False` is the solution

**Comment by YASHGUPTA2611** [comment]
Thanks @mikeejazmines , it worked
