### ISSUE TITLE
How to give flags or limit our buy and sell signal for the backtesting??

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#403]

**Comment by mikeejazmines** [comment]
Please give more details on the issue/ask

**Comment by RogerMichel** [comment]
Hi, similar question here I guess:
let's say i have buy/sell signals; but at every trade i want to simulate stop loss/stop profit; how can I take this into consideration in the backtesting?

Example:
2021/1/1 buy signal; i want to put stop loss at -1% and stop profit at +3%
2021/1/2 : market drop -2% so I want stop loss at -1% executed (even though no sell signal)
etc

Thanks!

**Comment by mikeejazmines** [comment]
@RogerMichel 

there is already stop loss and take profit (https://github.com/enzoampil/fastquant/blob/4683879bc51bac24fed2ff8bc52d1a528a9f2203/python/fastquant/strategies/base.py#L52-L54)

You simply need to state the number when you create the strategy https://github.com/enzoampil/fastquant/blob/4683879bc51bac24fed2ff8bc52d1a528a9f2203/python/fastquant/strategies/base.py#L386-L396

**Comment by YASHGUPTA2611** [comment]
Let's say i have initial_cash = 100000 and according to my strategy there are 3 buy signals in the starting and i wand to limit my buy signals to only one.
 So the below approach is right? or do we have any alternative?
![Capture11](https://user-images.githubusercontent.com/74678250/146890893-3dc0f2e5-6027-48f7-b76e-fa481357ecbd.PNG)
![Capture12](https://user-images.githubusercontent.com/74678250/146890900-cd41391e-8c18-43df-b55d-ec51cfba1d7a.PNG)

**Comment by mikeejazmines** [comment]
this will not work. 

def buy_signal you are defining a function which should be its own line. I highly suggest going over the backtrader quickstart guide https://www.backtrader.com/docu/quickstart/quickstart/

what fastquant does is handle the main backtrader so all you need is to create the buy_signal and sell_signal. no need to add count. it will automatically handle the signals and buy using the first signal. if there is another buy before a sell, it wont do anything

**Comment by YASHGUPTA2611** [comment]
Below is my strategy that i implemented.
![1](https://user-images.githubusercontent.com/74678250/147044380-80f4b82a-3223-4cef-9e10-e913f9337119.PNG)
![2](https://user-images.githubusercontent.com/74678250/147044386-9ae65de2-7fb3-4708-8010-46d416bb70b0.PNG)
In the starting my strategy takes the trade and buy 2 times then sell only one.
I only want to trade one time and will give buy prop and sell prop. How will i do it??

**Comment by mikeejazmines** [comment]
This is a case of slippage and this really happens even in real life scenarios. You can try changing the slippage to 0

**Comment by YASHGUPTA2611** [comment]
Okay understood @mikeejazmines .
Thanks for the reply.
