### ISSUE TITLE
How to get multiple dataframe and backtest at same time

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#405]

**Comment by mikeejazmines** [comment]
Please give more details on the issue/ask

**Comment by YASHGUPTA2611** [comment]
I have read the two dataframe using get_crpto_data.
![Capture22](https://user-images.githubusercontent.com/74678250/147216828-5fea0113-7c00-4c09-a79c-cdfdfa4d16cd.PNG)
![Capture21](https://user-images.githubusercontent.com/74678250/147216530-515a022b-27a5-4a8c-a573-64ba00c51b02.PNG)
Now i want to backtest both dataframe at once.
So, how will i do it??

**Comment by YASHGUPTA2611** [comment]
![Capture2](https://user-images.githubusercontent.com/74678250/147223208-d1cdb515-a8ed-4b92-b19b-c648777a82b4.PNG)
and it is giving me this error

**Comment by mikeejazmines** [comment]
Hi! I don't think your all_dataframe is a list of dataframes. It looks to be a list of string. If you see your screenshot it says `['dataframe_BTCUSDT', 'dataframe_ETHUSDT']` which suggests its a string.

**Comment by YASHGUPTA2611** [comment]
Hi @mikeejazmines 
![Capture12](https://user-images.githubusercontent.com/74678250/147233063-2f7cee4f-453e-4ab8-b00a-8abf8268eefa.PNG)
That i know, but in the above fig. it is also saying that if it is a string it will treat as a path. and i have saved the dataframe as csv file. But it is still showing me error

**Comment by YASHGUPTA2611** [comment]
Or do you have any alternative?, means how do i convert my string of dataframe that will pass on the backtest function.

**Comment by mikeejazmines** [comment]
you can store the dataframes in an array and loop through that array and pass each element into the backtest function

**Comment by YASHGUPTA2611** [comment]
But as far as i know, backtrader only read OHLC form of data. 
And also i have tried to combine many dataframes in one array, but it is showing me some error. 
So, it will be very helpful if you please provide the code for the same.

**Comment by mikeejazmines** [comment]
Yes, that is why i said store the dataframes in an array and loop through that array and pass _each_ element into the backtest function

```
dataframes = []
for tick in tickers:
    dataframes.append(get_crypto(tick, .....))

results = []
for df in dataframes:
    result = backtest(df, ...)
    results.append(result)
```

This is also not a backtrader or fastquant specific question. Please do limit the issues to fastquant related issues.

**Comment by YASHGUPTA2611** [comment]
Okay understood, Thank you for the reply.
