### ISSUE TITLE
Not able to import strategy class from another python file

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#406]
![Capture1](https://user-images.githubusercontent.com/74678250/147400582-b58142c9-71ba-4f34-9585-b1be2c23a1d8.PNG)

First i have made a strategy class in a separate python file and imported some of the libraries which will be use.

![Capture2](https://user-images.githubusercontent.com/74678250/147400624-9bf8ffe6-36ed-4d91-9c0c-caa6fe11a1cf.PNG)

but when i try to import my strategy class, it is giving me some error.

**Comment by mikeejazmines** [comment]
This may mean that in your strategy you are passing more than 2 elements when it is only expecting 2. (As stated in the ValueError)

I'd recommend looking at the indicators you are calling and what you are passing to them

**Comment by mikeejazmines** [comment]
Has this been addressed, may we close the issue?

**Comment by YASHGUPTA2611** [comment]
Yes, thankyou the issue has been resolved.
