### ISSUE TITLE
Backtest function not working while deploying flask application

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#407]
![Captureaa](https://user-images.githubusercontent.com/74678250/148511973-fd02414d-b6c9-4be4-ad31-79557d8e1405.PNG)

I have imported the backtest function but it is showing that backtest doesn't take init_cash argument and same for plot and other arguments.

![Capturebb](https://user-images.githubusercontent.com/74678250/148512222-00fb336c-e646-425b-84b2-aeb777ee8cd5.PNG)

![Captureff](https://user-images.githubusercontent.com/74678250/148512735-ea726a1b-e5f3-438d-9469-33228505007c.PNG)

Then i removed all other argument except strategy and df, then it is showing backtest takes only zero argument.

Please tell me how to sole this issue.

**Comment by mikeejazmines** [comment]
hi this issue was closed, has it been fixed?
