### ISSUE TITLE
How to get previous and current row while implementing the strategy

### ISSUE THREAD

**Issue by YASHGUPTA2611** [enzoampil/fastquant#408]
![Capture](https://user-images.githubusercontent.com/74678250/148888477-f0a65c9d-185a-41a1-a509-1caed388f39d.PNG)
Whats the difference if we put self.upperband[0], self.upperband[-1], self.upperband[1]?

I want to consider my upperband values a previous row and the closing price as current for the besting of my strategy.

**Comment by mikeejazmines** [comment]
For simple crossovers, i suggest using the crossover function https://www.backtrader.com/home/helloalgotrading/

it would be a much simpler implementation. also backtrader follows regular indexing in a timeseries, so 0, -1, 1 does the same as a regular timeseries

**Comment by YASHGUPTA2611** [comment]
ok understood, Thanks
