### ISSUE TITLE
[BUG] json_normalize issue

### ISSUE THREAD

**Issue by EngAhmedElkady** [enzoampil/fastquant#421]
from fastquant.disclosures.pse import DisclosuresPSE
  File "E:\AK Trading\Projects\test\env\Lib\site-packages\fastquant\disclosures\pse.py", line 24, in <module>
    from pandas.io.json import json_normalize
ImportError: cannot import name 'json_normalize' from 'pandas.io.json' (E:\AK Trading\Projects\test\env\Lib\site-packages\pandas\io\json\__init__.py)
#### Problem description

This error is occurring because the json_normalize function was moved from the pandas.io.json module to the top-level pandas module in Pandas version 1.0.0.

**Comment by msob** [comment]
I ran into the same problem and just created a pull request for this.
