### ISSUE TITLE
[FEATURE] implement smart caching for stock data

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#48]
We need to implement smart caching for `get_pse_data`, similar to `load_disclosures`. The former only checks for exact match of filename of saved stock data before loading; otherwise it re-downloads everything from scratch even if there's only 1 day difference between old and new query. The latter finds any saved discloures data of that company and appends older and/or newer data depending on the query so no data is downloaded twice.

**Comment by jpdeleon** [comment]
@jgendrinal Does your caching has the same as the latter behavior described above?

**Comment by jgendrinal** [comment]
Yup.

**Comment by jpdeleon** [comment]
Can you refer to the line? I want to see how you implement it in R.

**Comment by jpdeleon** [comment]
To make `get_pse_data` faster,
* include 5 years historical data of all symbols as cache in /data (~9MB)
* download only newer data if needed

**Comment by jgendrinal** [comment]
Will close my previous issue on this, but will add r-dev tag

**Comment by jgendrinal** [comment]
Need help handling this issue first https://github.com/enzoampil/fastquant/issues/57

**Comment by jgendrinal** [comment]
@jpdeleon, proposing alternative solution:
- Upon first use of `get_pse_data`, download 3 years worth of stock prices
- Store a csv file named with the ticker symbol and date range in /fq-data folder in current directory of the user

`get_pse_data` will then execute the following:
1. Check to see if symbol is found among files in /fq-data
2. Check to see if their query falls outside the date range
3. Query to API all necessary files
4. Cache additional to combined new csv file in /fq-data folder

**Comment by jgendrinal** [comment]
Temporarily closing caching until we can harmonize Python and R caching conventions.
