### ISSUE TITLE
[BUG] get_company_disclosures only returns first 50 results by default 

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#49]
As seen in [edge query form](https://edge.pse.com.ph/announcements/form.do), only the first 50 results are shown by default. We need to fix [`get_company_disclosures`](https://github.com/enzoampil/fastquant/blob/371ee005e1550a660eef8210a27a4e2eec080782/fastquant/disclosures.py#L138) to get the entire results.

@enzoampil can you check this? I really don't know how to solve this.

![DMC_disclosures](https://user-images.githubusercontent.com/15188345/79061646-57b76c80-7ccd-11ea-97fb-d59a9b430b06.png)

**Comment by enzoampil** [comment]
Will have to apply pagination to the get requests
