### ISSUE TITLE
[FEATURE] add a financial network analysis example

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#50]
I can add a financial network analysis example, following [Dr. Legara's notebook](https://github.com/eflegara/FinancialNetwork/blob/master/Financial%20Network.ipynb).

**Comment by enzoampil** [comment]
I like this. This can simultaneously act as marketing material on a blog, whether on Medium or straight in the fastquant website :)

**Comment by jpdeleon** [comment]
Here's the current network:

![network](https://user-images.githubusercontent.com/15188345/79341732-34a7e980-7f67-11ea-9ea5-0b49cc744aea.jpg)

**Comment by jpdeleon** [comment]
It'll be greate if we can make a "live" website that periodically updates this figure.

**Comment by jpdeleon** [comment]
First attempt at #63

**Comment by jpdeleon** [comment]
Fixed.
