### ISSUE TITLE
[BUG] site returns empty html

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#55]
Check why investagrams returns empty html:
https://github.com/enzoampil/fastquant/blob/9286b55aa5954bb0c69498869426e72a91f1645b/fastquant/disclosures.py#L584

**Comment by enzoampil** [comment]
@jpdeleon  Which date range does this happen. It may be because no earnings disclosures came out in your date range. The following works:

```
cd = DisclosuresInvestagrams(
    symbol='JFC', from_date='2018-12-01', to_date='2020-04-01'
)

cd.disclosures_json
```

**Comment by jpdeleon** [comment]
Right! I queried a short baseline from January this year and it returned html. I confirm using a longer baseline returns data. I will re-open this issue if any bug arises.
