### ISSUE TITLE
[BUG] phisix API endpoint deprecated

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#59]
The old phisix API endpoint:
http://phisix-api2.appspot.com/stocks/
has been replaced with a new one:
http://1.phisix-api.appspot.com/stocks/

The fix is implemented in #58 .

**Comment by jpdeleon** [comment]
Update: I put the old API back if new API fails, and I added a catch error if server error occurs.

**Comment by jgendrinal** [comment]
Need to implement this in R as well if the endpoint is deprecated before resolving https://github.com/enzoampil/fastquant/issues/48 from my end
