### ISSUE TITLE
[FEATURE] return cerebro object instead of bool in backtest

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#65]
https://github.com/enzoampil/fastquant/blob/36fc7cadb10871641a0e6a314705165ea68a3c90/fastquant/strategies.py#L536

After running backtest, it'll be better to return the cerebro object in case user needs to access its properties (at least I do).

@enzoampil Do you agree? I will do this if so.

**Comment by enzoampil** [comment]
Ok this is a NEED.

**Comment by enzoampil** [comment]
@jpdeleon thanks for catching this. Yes, intended the boolean as a temporary thing to return.
