### ISSUE TITLE
[BUG] Error when running the get_pse_data from lesson 1 (fresh installation)

### ISSUE THREAD

**Issue by alexismanalo** [enzoampil/fastquant#66]
#### Problem description

I'm unable to run the "three line code" from lesson 1

Initially, installed fastquant in Anaconda terminal using
```python
pip install git+git://github.com/enzoampil/fastquant.git
```
Proceeded to open my Jupyter notebook to run the following codes
```python
from fastquant import get_pse_data
df = get_pse_data('JFC', '2018-01-01', '2019-01-01')
df.head()
```

Error showed

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-1-9c79d47d26a0> in <module>
>       1 from fastquant import get_pse_data
> ----> 2 df = get_pse_data('JFC', '2018-01-01', '2019-01-01')
>       3 df.head()
> 
> C:\ProgramData\Anaconda3\lib\site-packages\fastquant\fastquant.py in get_pse_data(symbol, start_date, end_date, save, max_straight_nones, format)
>     404             )
>     405     else:
> --> 406         cache = get_pse_data_cache(symbol=symbol)
>     407         cache = cache.reset_index()
>     408         # oldest_date = cache["dt"].iloc[0]
> 
> C:\ProgramData\Anaconda3\lib\site-packages\fastquant\fastquant.py in get_pse_data_cache(symbol, cache_fp, update, verbose)
>     303         print("Loaded: ", cache_fp)
>     304     errmsg = "Cache does not exist! Try update=True"
> --> 305     assert cache_fp.exists(), errmsg
>     306     df = pd.read_csv(cache_fp, index_col=0, header=[0, 1])
>     307     df.index = pd.to_datetime(df.index)
> 
> AssertionError: Cache does not exist! Try update=True
> 
![image](https://user-images.githubusercontent.com/10992865/80801364-b130fe00-8bde-11ea-928b-8d9cd1bfb5c0.png)

Downloaded the "data" folder from fastquant repo and pasted in my installation directory
> C:\ProgramData\Anaconda3\Lib\site-packages\fastquant

Re-ran my Jupyter notebook and re-ran
```python
from fastquant import get_pse_data
df = get_pse_data('JFC', '2018-01-01', '2019-01-01')
df.head()
```

Same error message.

**Comment by enzoampil** [comment]
@jpdeleon were able to replicate this issue by any chance?

**Comment by enzoampil** [comment]
I was able to replicate the error, just wondering why this doesn't reflect in the fastquant [tests](https://github.com/enzoampil/fastquant/blob/master/tests/test_fastquant.py).

**Comment by enzoampil** [comment]
@jpdeleon Why do we assert the existence of the [cache](https://github.com/enzoampil/fastquant/blob/36fc7cadb10871641a0e6a314705165ea68a3c90/fastquant/fastquant.py#L305) again?

**Comment by enzoampil** [comment]
@jpdeleon think we can set `update=True` when the file path doesnt exist?

**Comment by jpdeleon** [comment]
Proposed a fix at #67

**Comment by alexismanalo** [comment]
Not sure if this helps but I'm able to successfully run a code using the following:

```python
from fastquant import get_pse_data_old
df = get_pse_data_old('MPI', '2018-01-01', '2019-01-01')
df.head()
```

**Comment by jpdeleon** [comment]
Hi @alexismanalo , thanks for your interest! And sorry for such a trivial bug. I just proposed a fixed and it is currently under review. If you want to use the fix for now, please re-install the tests branch of fastquant using:

```
!pip install -U git+https://github.com/enzoampil/fastquant.git@tests
```

You can use the `get_pse_data_old` but it gives you `date`, `open`, `high`, `low`, `close` columns  only. To backtest, you need the `volume` too and that is provided by `get_pse_data`.

**Comment by alexismanalo** [comment]
Thanks @jpdeleon , no worries! I tried the tests branch and seems to be working fine. I might be getting a few NaN's though for recent data pulls (2020) but, hey, that's for another day.

Thanks, again for your hard work.

**Comment by enzoampil** [comment]
@jpdeleon I've updated pypi, with the above merged update but I'm still getting this bug (even if above installation works).

```
df = get_stock_data('JFC', "2018-01-01", '2019-01-01')

Cache does not exist! Try update=True
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-276201243700> in <module>()
----> 1 df = get_stock_data('JFC', "2018-01-01", '2019-01-01')

1 frames
/usr/local/lib/python3.6/dist-packages/fastquant/fastquant.py in get_pse_data(symbol, start_date, end_date, save, max_straight_nones, format)
    409     else:
    410         cache = get_pse_data_cache(symbol=symbol)
--> 411         cache = cache.reset_index()
    412         # oldest_date = cache["dt"].iloc[0]
    413         newest_date = cache["dt"].iloc[-1]

AttributeError: 'NoneType' object has no attribute 'reset_index'
```

Any ideas why?

**Comment by enzoampil** [comment]
**Found the fix:**
Have to exlicitly upload data files to pypi in `setup.py` ([reference](https://stackoverflow.com/questions/57748325/how-to-create-and-load-internal-data-in-python-package)).

These are reflected in the commit above to master.

@alexismanalo Installing fastquant regulary with `pip install fastquant` should also work now :smile:

**Comment by alexismanalo** [comment]
@enzoampil The fix worked fine. Should be okay to close this one. Thanks, again! 😃

**Comment by jpdeleon** [comment]
@alexismanalo Just remember you can get either date,close,volume columns (format='dcv') or date,open,high,low,close columns (format='dohlc') but NOT a mix of columns from the two groups (e.g. format='docv' yields NaN in Open column). The reason is their sources are different. Will try a fix but this suffice for now.
