### ISSUE TITLE
local pip install error and fix

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#7]
I installed psequant using `pip install psequant` and it worked alright.
When you pushed an update in `get_company_disclosures()`, I tried to `pip install psequant --upgrade` but it didn't seem to have the latest commit.

So I tried to clone your repo and install locally in develop mode using `pip install -e .` so I have to git pull only to reflect the recent updates.

Doing so throwed an error:

```
Building wheel for psequant (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jp/miniconda3/envs/py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mhaabhka/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mhaabhka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tn2238pz --python-tag cp37
       cwd: /tmp/pip-req-build-mhaabhka/
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/psequant
  copying psequant/psequant.py -> build/lib/psequant
  copying psequant/__init__.py -> build/lib/psequant
  running build_scripts
  creating build/scripts-3.7
  error: [Errno 21] Is a directory: 'psequant'
  ----------------------------------------
  ERROR: Failed building wheel for psequant
```

I figured that the path to the script in setup.py should be `psequant/psequant` instead. Since that script is still a template, i recommend to remove it in setup.py for the meantime .

**Comment by enzoampil** [comment]
Can you try ```pip install psequant --upgrade``` again. It should be reflected now :)
