### ISSUE TITLE
Date not showing at xaxis. Kindly fix. Love your work!

### ISSUE THREAD

**Issue by ntanii23** [enzoampil/fastquant#72]
![Figure_1](https://user-images.githubusercontent.com/31375991/80856293-3c5fd180-8c7b-11ea-9df1-f5573cdecaf6.png)

**Comment by jpdeleon** [comment]
Hi @ntanii23 , did you see the template questions when reporting this bug? If not, here it is:
```
<!-- Fill in the information below before opening an issue. -->

#### Problem description
<!-- Provide a clear and concise description of the issue. -->

#### Example
<!-- Provide a link or minimal code snippet that demonstrates the issue. -->
```python
import fastquant
# insert code here ...
```

#### Expected behavior


#### Environment

-  platform (e.g. Linux, OSX, Windows):
-  fastquant version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):
```

If you use pandas, you can do the ff:
```python
from fastquant import get_stock_data
import pandas as pd

df = get_stock_data('JFC', '2018-01-01', '2019-01-01', format='dc')

#set dt as datetime object
df['dt'] = pd.to_datetime(df.dt)
#set dt as index
df = df.set_index('dt')
df.plot()
```

**Comment by ntanii23** [comment]
thank you very much

**Comment by jpdeleon** [comment]
Welcome! If you don't have any related issue, then I will close this now. Please re-open whenever you find any problems.
