### ISSUE TITLE
bug template

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#74]
Please fix the bug report template below, specifically the 2nd to the last line:
```
-  lightkurve version (e.g. 1.0b6): <-- We need to take note of fastquant versioning
```
to something like
```
-  fastquant version (e.g. 1.0)
```
It'll be better if version can be printed via the stardard means
```python
import fastquant
fastquant.__version__
```
but not sure how. May be adding a `version.py` and importing in `__init__`?

#### Example

```python
import fastquant
# insert code here ...
```

#### Environment

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by jpdeleon** [comment]
@enzoampil can you quickly resolve this so we can close.

**Comment by enzoampil** [comment]
As a quick fix, I just changed to requesting for fastquant version.
