### ISSUE TITLE
[FEATURE] Apply automated grid search straight from `backtest`

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#75]
Currently the `backtest` function only takes on one set of arguments at a time. In practice we actually want to run results on multiple combinations. (e.g. multiple possible values for slow and fast moving average).

Utilize `cerebro.optstrategy` to perform the above ([reference](https://www.backtrader.com/docu/cerebro/))

**Comment by jpdeleon** [comment]
Once done, we can mention in the [notebook](https://github.com/enzoampil/fastquant/blob/master/examples/backtest_with_grid_search.ipynb) that fastquant does this automatically for user. :) 

I think this merits backtest to be a class of its own so we access it's properties e.g. the best parameters, the backtrader figure using the best parameters, etc.

**Comment by enzoampil** [comment]
@jpdeleon Noted on the notebook :)

hmm not necessary for it to have its own class if all of these properties are found straight from the cerebro object rigth?

**Comment by jpdeleon** [comment]
@enzoampil I agree. Sorry I missed earlier your note about `cerebro.optstrategy` that does parameter optimization under the hood already. I think any parameter in a strategy can be optimized already.

The grid_search notebook is only useful for presentation but not useful in practice. 

Also check also this backtrader [script](https://github.com/mementum/backtrader/blob/master/samples/optimization/optimization.py) that optimizes across strategies.

**Comment by enzoampil** [comment]
Planning to apply the ff:

1. Perform grid search if any of the parameters are input as an `iterable`
2. If `plot = True` only the "optimal" version of the strategy is returned
