### ISSUE TITLE
[BUG] no stock data returned when date inputs are valid but incorrect 

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#76]
#### Problem description
`get_stock_data(..., format='dcv')` throws error/ quits prematurely when `start_date` input is much earlier than when data is available. This happens because we set 10 consecutive NaNs as threshold for escaping the loop. Ideal solution is to figure out if date inputs are wrong and prescribe the correct date, or just return available data even if far from either dates without raising an exception. I prefer the first solution so it notifies the user that requested data on date is unavailable.

Note: We can also refer to [listing date column](https://github.com/enzoampil/fastquant/blob/master/fastquant/data/stock_table.csv) as earliest possible `start_date` input especially for new companies enlisted in the last 5 years. Some companies are listed decades ago, but why data stock data is available only recently? 

#### Example
```python
from fastquant import get_stock_data
df = get_stock_data("MAH", start_date="2018-01-01", end_date="2020-01-01", format="dcv")
```
throws error, whereas the one below does not 
```python
df = get_stock_data("MAH", start_date="2019-01-01", end_date="2020-01-01", format="dcv")
```

I found from data cache that MAH has data only from "2018-06-04". Probably a fix is to assert `start_date`>first date entry in cache, if it exists and additionally add a note to user to use later dates when Exception arises. We may need to add a custom exception handler for this.

**Comment by alswang18** [comment]
I don't think this is still an error anymore. The format 'dcv' doesn't seem to exist anymore either.

**Comment by enzoampil** [comment]
Thanks @alswang18 , looks like we can close this issue then.
