### ISSUE TITLE
[FEATURE] Auto detect format of dataframe to be backtested based on column names

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#83]
Right now, only `cv` and `c` are registered data formats (see below). 

We can automate this by using the standard column names to automatically populate the indices to the format `dict` rather than having to *manually* register data formats.

```
DATA_FORMAT_MAPPING = {
    "cv": {
        "datetime": 0,
        "open": None,
        "high": None,
        "low": None,
        "close": 1,
        "volume": 2,
        "openinterest": None,
    },
    "c": {
        "datetime": 0,
        "open": None,
        "high": None,
        "low": None,
        "close": 1,
        "volume": None,
        "openinterest": None,
    }
}
```

**Comment by jpdeleon** [comment]
I tried to do a function that outputs the format mapping before but it’s quite tricky.

**Comment by enzoampil** [comment]
Same experience. It initially seemed trivial, but ... apparently not

**Comment by enzoampil** [comment]
Prioritizing this as we've been getting requests for strategies that go beyond "closing" based indicators.
