### ISSUE TITLE
[BUG] Plotting doesn't work on google Colab

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#89]
On of the main features of the `backtest` function is your ability to plot you backtests. Currently plotting does not work when run on a Colab notebook.

Sample code:

```
from fastquant import get_stock_data, backtest
df = get_stock_data('BLOOM', '2018-01-01', '2020-05-10')
res = backtest("rsi", df, rsi_upper=range(60, 90, 5), rsi_lower=range(10, 30, 5), verbose=False, plot=True)
```

**Comment by jpdeleon** [comment]
@enzoampil Isn't this related to `get_stock_data` having implicit format='c', instead of 'cv'?

**Comment by enzoampil** [comment]
Ah no, the plotting in the `backtest` function should still work with the `c` format. It just stops plotting volume in that case but should still work.

**Comment by rafmacalaba** [comment]
@jpdeleon  @enzoampil I solved this by adding a parameter in `cerebro.plot(iplot=False)` when using Colab. maybe we can have a variable that the user can set to boolean if they are running in Colab or not.

**Comment by enzoampil** [comment]
awesome @rafmacalaba . Feel free to send a PR for this :) awesome finding!
