### ISSUE TITLE
fastquant not compatible with new pandas version 1.0

### ISSUE THREAD

**Issue by ecolbinado** [enzoampil/fastquant#9]
`ERROR: fastquant 0.1.2.5 has requirement pandas==0.25.3, but you'll have pandas 1.0.0 which is incompatible.`

I just upgraded to pandas 1.0 and found out that fastquant package is not yet compatible with it. Not a severe issue since I can just rollback to 0.25 version and given pandas 1.0 is very new.

**Comment by enzoampil** [comment]
Thanks for bringing this up @ecolbinado ! Yes, agree that pandas 1.0 is new andwill wait out for a bit before integrating it. I suggest that you install `fastquant` in a fresh virtual environment when you use it :)
