### ISSUE TITLE
[FEATURE] add crypto 

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#92]
It'll be interesting to add the ability to pull and backtest crypto data (at least major ones like bitcoin, ethereum, etc) with fastquant. 
Here are some api's that provide crypto data:
* [quandl](https://blog.quandl.com/api-for-bitcoin-data): e.g. https://www.quandl.com/api/v3/datasets/BCHARTS/BITSTAMPUSD
* others that doesn't need api key?

See also [this notebook](https://blog.patricktriest.com/analyzing-cryptocurrencies-python/) about basic crypto analysis.

**Comment by enzoampil** [comment]
Very interested in this. Quite relevant as well with the increase in bitcoin adoption atm!

**Comment by enzoampil** [comment]
References:

https://github.com/pycrypto/pycrypto
https://github.com/pyca/cryptography
https://github.com/ethereum/pyethereum
https://github.com/freqtrade/freqtrade

**Comment by enzoampil** [comment]
Use binance

**Comment by jpdeleon** [comment]
a more extensive api list: https://github.com/ccxt/ccxt

**Comment by tunedforai** [comment]
If you're still looking for a crypto data source, x402.tunedfor.ai has live snapshots (price, funding, OI, CVD, buy/sell ratio, fear/greed) and historical OHLCV for BTC, ETH, SOL, etc. No API key — pay per call in USDC. Could slot into a backtest pipeline without subscription overhead. .20 for snapshot, -5 for history depending on granularity.
