### ISSUE TITLE
[BUG] some functions in video tutorial are deprecated

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#97]
For example, `get_company_disclosures` demonstrated here:
https://www.youtube.com/watch?v=Yf0nZ7C45zY&t=45m29s
is not available anymore since I migrated it into the `DisclosuresPSE` class.

This is probably how a new user stumbled upon it and reported it as a bug: 
https://github.com/enzoampil/fastquant/issues/5#issuecomment-634449661

One quick fix is to make it available both as a standalone function and a method, although I prefer it used as a method so user can access more attributes in the class such as plotting etc. At least they won't be confused with the bug if they follow the tutorial.

@enzoampil what do you think?

**Comment by enzoampil** [comment]
Hmmmmm, initial thought is to just add a note in the video that there a new way to call the function. Should be ok to keep module as is :)
